name: Latest Versions Check

on: [pull_request]

jobs:
  versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 21
      - run: ./mvnw clean versions:update-properties scm:check-local-modification -U -B