name: OWASP Dependency Check

on: [pull_request]

jobs:
  owasp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 21
      - run: ./mvnw clean dependency-check:check -B